/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSignalsRouteImport } from './routes/app.signals'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppFeedRouteImport } from './routes/app.feed'
import { Route as AppExecutionRouteImport } from './routes/app.execution'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionRoute = AppExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/execution': typeof AppExecutionRoute
  '/app/feed': typeof AppFeedRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/execution': typeof AppExecutionRoute
  '/app/feed': typeof AppFeedRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/execution': typeof AppExecutionRoute
  '/app/feed': typeof AppFeedRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/signals': typeof AppSignalsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/execution'
    | '/app/feed'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/risk'
    | '/app/settings'
    | '/app/signals'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/execution'
    | '/app/feed'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/risk'
    | '/app/settings'
    | '/app/signals'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/execution'
    | '/app/feed'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/risk'
    | '/app/settings'
    | '/app/signals'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/signals': {
      id: '/app/signals'
      path: '/signals'
      fullPath: '/app/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/execution': {
      id: '/app/execution'
      path: '/execution'
      fullPath: '/app/execution'
      preLoaderRoute: typeof AppExecutionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExecutionRoute: typeof AppExecutionRoute
  AppFeedRoute: typeof AppFeedRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExecutionRoute: AppExecutionRoute,
  AppFeedRoute: AppFeedRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppRiskRoute: AppRiskRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
